### ISSUE TITLE
Problem mit terminal42/contao-ajaxform

### ISSUE THREAD

**Issue by Schmidty2** [heimseiten/contao-scroll-to-error-bundle#1]
Hallo,
ich habe gerade festgestellt, dass nicht zum Fehler gescrollt wird, wenn terminal42/contao-ajaxform verwendet wird.
Lässt sich das korrigieren und die Erweitereung auch gleich für Contao 5.3 fit machen (abwärtskompatibel bis Contao 4.13)?
Terminal42/contao-ajaxform ist ja seit Contao 5.1 im Core enthalten.
Je nach Aufwand, kann ein ich einen Teil mit finanzieren.
Wegen des Preises Rückmeldung bitte per PN, Danke.

**Comment by heimseiten** [comment]
Hallo, die Funktionalität der Erweiterung wurde ich der Erweiterung https://github.com/heimseiten/contao-custom-contao-bundle übernommen, welche mit Contao 5 kompatibel ist. 

Ich schaffe das Problem gerade gar nicht zu reproduzieren, da bevor das Formular abgesendet wird, schon ein Meldung kommt "Fülle dieses Feld aus".

**Comment by Schmidty2** [comment]
Hallo,
Danke für die Info :-)
Ich schaue mir die Deine neue Erweiterung an, wenn ich nicht klar komme, melde ich mich.
